#pragma once
#include "CoreMinimal.h"
#include "EMapArea.generated.h"

UENUM(BlueprintType)
enum class EMapArea : uint8 {
    Lobby,
    LobbySecondFloor,
    LobbyElevatorUnload,
    LobbyElevatorTop,
    FoodCourt,
    FCPipeToGG,
    GatorGolfStomachRoom,
    GatorGolfBathrooms,
    GatorGolfMontyCamera,
    GatorGolfStairs,
    GatorGolfMainArea,
    GatorGolfKitchen,
    GatorGolfBackHall,
    GatorGolfBackOffice,
    DaycareLoadWarehouse,
    DaycareTransitionRoom,
    UnloadGolfAtDCEntrance,
    DaycarePlayArea,
    DaycareBallPitEntrance,
    DaycareBallPitSlide,
    DaycareEclipseTransition,
    DaycarePlayAreaExit,
    DaycareTheater,
    DaycareUnloadPlayArea,
    CatwalksVent,
    MontyRide,
    CatwalksMainArea,
    CatwalksSectionThree,
    CupcakesPrepRoom,
    Cupcakes,
    CupcakesUnloadPrepRoom,
    CupcakesPrepToMain,
    CupcakesBackRoom,
    ServerRoom,
    Salon,
    SalonLogRide,
    LogRide,
    UnloadLogRide,
    RacewayPartOne,
    UnloadRacewayPartOne,
    BonnieBowl,
    FazerBlastOffice,
    FazerBlastOfficeVent,
    FazerBlastOfficeCatwalks,
    FazerBlastMainArea,
    FazerblastExitVent,
    FazerBlastTransition,
    RacewayPartTwoDoors,
    RacewayPartTwoGarages,
    RacewayUnloadTransitionRoom,
    RacewayPartTwo,
    Sinkhole,
};

